export const PICK_ROTATION_CARD = "PICK_ROTATION_CARD";
export const SET_DECK_ID = "SET_DECK_ID";
export const PICK_CARDS = "PICK_CARDS";
export const REORDER_WITH_ROTATION_CARD = "REORDER_WITH_ROTATION_CARD";
export const STACK_DECK = "STACK_DECK";
