export const PICK_ROTATION_CARD = "PICK_ROTATION_CARD";
export const PICK_CARDS = "PICK_CARDS";
export const REORDER_WITH_ROTATION_CARD = "REORDER_WITH_ROTATION_CARD";
export const STACK_DECK = "STACK_DECK";
